//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Core.GraphicalUIs.ToolStrips {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuText() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Core.GraphicalUIs.ToolStrips.MenuText", typeof(MenuText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ClearSelection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit_ClearSelection {
            get {
                return ResourceManager.GetString("Edit_ClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit_Copy {
            get {
                return ResourceManager.GetString("Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit_Cut {
            get {
                return ResourceManager.GetString("Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit_Delete {
            get {
                return ResourceManager.GetString("Edit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit_Paste {
            get {
                return ResourceManager.GetString("Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit_Redo {
            get {
                return ResourceManager.GetString("Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SelectAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit_SelectAll {
            get {
                return ResourceManager.GetString("Edit_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit_Undo {
            get {
                return ResourceManager.GetString("Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Exit {
            get {
                return ResourceManager.GetString("File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Newfile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Newfile {
            get {
                return ResourceManager.GetString("File_Newfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Open {
            get {
                return ResourceManager.GetString("File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Print {
            get {
                return ResourceManager.GetString("File_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PrintPreview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_PrintPreview {
            get {
                return ResourceManager.GetString("File_PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Reload {
            get {
                return ResourceManager.GetString("File_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Save {
            get {
                return ResourceManager.GetString("File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_SaveAll {
            get {
                return ResourceManager.GetString("File_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveAs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_SaveAs {
            get {
                return ResourceManager.GetString("File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InstallThemepack: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tool_InstallThemepack {
            get {
                return ResourceManager.GetString("Tool_InstallThemepack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InstallThemepack_Confirm: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tool_InstallThemepack_Confirm {
            get {
                return ResourceManager.GetString("Tool_InstallThemepack_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InstallThemepack_StatusMsg: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tool_InstallThemepack_StatusMsg {
            get {
                return ResourceManager.GetString("Tool_InstallThemepack_StatusMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool_InstallThemepack_StatusMsg_Cancel: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tool_InstallThemepack_StatusMsg_Cancel {
            get {
                return ResourceManager.GetString("Tool_InstallThemepack_StatusMsg_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ArrangeIcons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_ArrangeIcons {
            get {
                return ResourceManager.GetString("Window_ArrangeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cascade に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_Cascade {
            get {
                return ResourceManager.GetString("Window_Cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CloseAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_CloseAll {
            get {
                return ResourceManager.GetString("Window_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_Hori {
            get {
                return ResourceManager.GetString("Window_Hori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_Vert {
            get {
                return ResourceManager.GetString("Window_Vert", resourceCulture);
            }
        }
    }
}
