//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yencon.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yencon.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   InvalidHeaderException_Signature に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHeaderException_Signature {
            get {
                return ResourceManager.GetString("InvalidHeaderException_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidHeaderException_Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHeaderException_Size {
            get {
                return ResourceManager.GetString("InvalidHeaderException_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidKeyNameException_Message {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidKeyNameException_Message {
            get {
                return ResourceManager.GetString("InvalidKeyNameException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidSyntaxException_InnerException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidSyntaxException_InnerException {
            get {
                return ResourceManager.GetString("InvalidSyntaxException_InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidSyntaxException_UnexpectedChar {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidSyntaxException_UnexpectedChar {
            get {
                return ResourceManager.GetString("InvalidSyntaxException_UnexpectedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidSyntaxException_UnexpectedToken {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidSyntaxException_UnexpectedToken {
            get {
                return ResourceManager.GetString("InvalidSyntaxException_UnexpectedToken", resourceCulture);
            }
        }
    }
}
