//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Core.Settings.YenconTool {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Core.Settings.YenconTool.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AddedKey Successfully に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddedKey_Successfully {
            get {
                return ResourceManager.GetString("AddedKey_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AddedSection Successfully に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddedSection_Successfully {
            get {
                return ResourceManager.GetString("AddedSection_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CannotDelete, KeyNotFound に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CmdHelp/Recognize Uppercase/Lowercase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp {
            get {
                return ResourceManager.GetString("CmdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_Add {
            get {
                return ResourceManager.GetString("CmdHelp_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_Clear {
            get {
                return ResourceManager.GetString("CmdHelp_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete, Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_DelRmv {
            get {
                return ResourceManager.GetString("CmdHelp_DelRmv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End, Exit, Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_EndExitQuit {
            get {
                return ResourceManager.GetString("CmdHelp_EndExitQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goroot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_Goroot {
            get {
                return ResourceManager.GetString("CmdHelp_Goroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G/Set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_Gset {
            get {
                return ResourceManager.GetString("CmdHelp_Gset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_Help {
            get {
                return ResourceManager.GetString("CmdHelp_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Into に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_Into {
            get {
                return ResourceManager.GetString("CmdHelp_Into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_List {
            get {
                return ResourceManager.GetString("CmdHelp_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List Full に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_ListFull {
            get {
                return ResourceManager.GetString("CmdHelp_ListFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make Section に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_Mks {
            get {
                return ResourceManager.GetString("CmdHelp_Mks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_Reload {
            get {
                return ResourceManager.GetString("CmdHelp_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_Save {
            get {
                return ResourceManager.GetString("CmdHelp_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_SaveB {
            get {
                return ResourceManager.GetString("CmdHelp_SaveB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CmdHelp_SaveT {
            get {
                return ResourceManager.GetString("CmdHelp_SaveT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CommandLine Invalid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommandLine_Invalid {
            get {
                return ResourceManager.GetString("CommandLine_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CommandNotFound: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted Successfully に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Deleted_Successfully {
            get {
                return ResourceManager.GetString("Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileNotFound: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KeyIsNotSection: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyIsNotSection {
            get {
                return ResourceManager.GetString("KeyIsNotSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KeyNotFound: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KindOfKey: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KindOfKey {
            get {
                return ResourceManager.GetString("KindOfKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NewValueOfKey: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewValueOfKey {
            get {
                return ResourceManager.GetString("NewValueOfKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reloaded Successfully に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reloaded_Successfully {
            get {
                return ResourceManager.GetString("Reloaded_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved Successfully に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Saved_Successfully {
            get {
                return ResourceManager.GetString("Saved_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SectionList_Empty {
            get {
                return ResourceManager.GetString("SectionList_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Present: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SectionList_Present {
            get {
                return ResourceManager.GetString("SectionList_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TempID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TempID {
            get {
                return ResourceManager.GetString("TempID", resourceCulture);
            }
        }
    }
}
