//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExplorerTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExplorerTexts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Resources.ExplorerTexts", typeof(ExplorerTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   BtnCollapse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnCollapse {
            get {
                return ResourceManager.GetString("BtnCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BtnExpand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnExpand {
            get {
                return ResourceManager.GetString("BtnExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BtnRefresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Msgbox_CannotChangeName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msgbox_CannotChangeName {
            get {
                return ResourceManager.GetString("Msgbox_CannotChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Msgbox_CannotCreate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msgbox_CannotCreate {
            get {
                return ResourceManager.GetString("Msgbox_CannotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Msgbox_CannotDelete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msgbox_CannotDelete {
            get {
                return ResourceManager.GetString("Msgbox_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Msgbox_CannotOpenIn_DefaultApp {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msgbox_CannotOpenIn_DefaultApp {
            get {
                return ResourceManager.GetString("Msgbox_CannotOpenIn_DefaultApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   additem に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Additem {
            get {
                return ResourceManager.GetString("PopupMenu_Additem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bash に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Bash {
            get {
                return ResourceManager.GetString("PopupMenu_Bash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   clone に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Clone {
            get {
                return ResourceManager.GetString("PopupMenu_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cmd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Cmd {
            get {
                return ResourceManager.GetString("PopupMenu_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Copy {
            get {
                return ResourceManager.GetString("PopupMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   createDir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_CreateDir {
            get {
                return ResourceManager.GetString("PopupMenu_CreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   createFile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_CreateFile {
            get {
                return ResourceManager.GetString("PopupMenu_CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Cut {
            get {
                return ResourceManager.GetString("PopupMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   defaultApp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_DefaultApp {
            get {
                return ResourceManager.GetString("PopupMenu_DefaultApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Delete {
            get {
                return ResourceManager.GetString("PopupMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Explorer {
            get {
                return ResourceManager.GetString("PopupMenu_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   openIn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_OpenIn {
            get {
                return ResourceManager.GetString("PopupMenu_OpenIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Paste {
            get {
                return ResourceManager.GetString("PopupMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   powershell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_PowerShell {
            get {
                return ResourceManager.GetString("PopupMenu_PowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Property {
            get {
                return ResourceManager.GetString("PopupMenu_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupMenu_Rename {
            get {
                return ResourceManager.GetString("PopupMenu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RemovedTreeNode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemovedTreeNode {
            get {
                return ResourceManager.GetString("RemovedTreeNode", resourceCulture);
            }
        }
    }
}
