//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormSettingsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormSettingsRes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Resources.FormSettingsRes", typeof(FormSettingsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   FormSettings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Environment_Caption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Environment_Caption {
            get {
                return ResourceManager.GetString("Environment_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Environment_labelDesc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Environment_labelDesc {
            get {
                return ResourceManager.GetString("Environment_labelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Environment_useExdialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Environment_useExdialog {
            get {
                return ResourceManager.GetString("Environment_useExdialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Environment_useWsl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Environment_useWsl {
            get {
                return ResourceManager.GetString("Environment_useWsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup_allowRisky に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startup_allowRisky {
            get {
                return ResourceManager.GetString("Startup_allowRisky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup_Caption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startup_Caption {
            get {
                return ResourceManager.GetString("Startup_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup_labelDesc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startup_labelDesc {
            get {
                return ResourceManager.GetString("Startup_labelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup_labelLang に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startup_labelLang {
            get {
                return ResourceManager.GetString("Startup_labelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup_riskySettings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startup_riskySettings {
            get {
                return ResourceManager.GetString("Startup_riskySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup_showDelMenu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startup_showDelMenu {
            get {
                return ResourceManager.GetString("Startup_showDelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup_visualstyle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Startup_visualstyle {
            get {
                return ResourceManager.GetString("Startup_visualstyle", resourceCulture);
            }
        }
    }
}
