//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormMainRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormMainRes() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Resources.FormMainRes", typeof(FormMainRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Error_CannotRetry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_CannotRetry {
            get {
                return ResourceManager.GetString("Error_CannotRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogoFormMain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CapturedActive {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_CapturedActive {
            get {
                return ResourceManager.GetString("Status_CapturedActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CapturedEntire に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_CapturedEntire {
            get {
                return ResourceManager.GetString("Status_CapturedEntire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status_NotSupported {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_NotSupported {
            get {
                return ResourceManager.GetString("Status_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preparing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_Preparing {
            get {
                return ResourceManager.GetString("Status_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WindowChanged {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_WindowChanged {
            get {
                return ResourceManager.GetString("Status_WindowChanged", resourceCulture);
            }
        }
    }
}
