//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogOutputTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogOutputTexts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Resources.LogOutputTexts", typeof(LogOutputTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   btnRefresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   col_CreatedDate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string col_CreatedDate {
            get {
                return ResourceManager.GetString("col_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   col_Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string col_Level {
            get {
                return ResourceManager.GetString("col_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   col_Logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string col_Logger {
            get {
                return ResourceManager.GetString("col_Logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   col_Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string col_Message {
            get {
                return ResourceManager.GetString("col_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lblCount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblCount {
            get {
                return ResourceManager.GetString("lblCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lblLevel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblLevel {
            get {
                return ResourceManager.GetString("lblLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lblLogger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string lblLogger {
            get {
                return ResourceManager.GetString("lblLogger", resourceCulture);
            }
        }
    }
}
