//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuTexts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Resources.MenuTexts", typeof(MenuTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   EDIT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FILE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Exit {
            get {
                return ResourceManager.GetString("File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_Save {
            get {
                return ResourceManager.GetString("File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_SaveAll {
            get {
                return ResourceManager.GetString("File_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveAllAs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_SaveAllAs {
            get {
                return ResourceManager.GetString("File_SaveAllAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveAs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File_SaveAs {
            get {
                return ResourceManager.GetString("File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HELP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SCREEN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CaptureActive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Screen_CaptureActive {
            get {
                return ResourceManager.GetString("Screen_CaptureActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CaptureEntire に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Screen_CaptureEntire {
            get {
                return ResourceManager.GetString("Screen_CaptureEntire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOOL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DesktopThemepacks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tool_DesktopThemepacks {
            get {
                return ResourceManager.GetString("Tool_DesktopThemepacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DesktopThemepacks_Confirm {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tool_DesktopThemepacks_Confirm {
            get {
                return ResourceManager.GetString("Tool_DesktopThemepacks_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DesktopThemepacks_Text {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tool_DesktopThemepacks_Text {
            get {
                return ResourceManager.GetString("Tool_DesktopThemepacks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VIEW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string View_LogOutput {
            get {
                return ResourceManager.GetString("View_LogOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput_CannotShow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string View_LogOutput_CannotShow {
            get {
                return ResourceManager.GetString("View_LogOutput_CannotShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WINDOW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arricons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_Arricons {
            get {
                return ResourceManager.GetString("Window_Arricons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cascade に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_Cascade {
            get {
                return ResourceManager.GetString("Window_Cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CloseActiveWnd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_CloseActiveWnd {
            get {
                return ResourceManager.GetString("Window_CloseActiveWnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CloseAllWnds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_CloseAllWnds {
            get {
                return ResourceManager.GetString("Window_CloseAllWnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hori に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_Hori {
            get {
                return ResourceManager.GetString("Window_Hori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SwitchWnd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_SwitchWnd {
            get {
                return ResourceManager.GetString("Window_SwitchWnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Window_Vert {
            get {
                return ResourceManager.GetString("Window_Vert", resourceCulture);
            }
        }
    }
}
