//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TerminalTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalTexts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Resources.TerminalTexts", typeof(TerminalTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   btnRefresh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string btnRefresh {
            get {
                return ResourceManager.GetString("btnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_Attributes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_Attributes {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_Attributes_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_Attributes_Description {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_Attributes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_CanAccess に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_CanAccess {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_CanAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_CanAccess_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_CanAccess_Description {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_CanAccess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_FileFormat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_FileFormat {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_FileFormat_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_FileFormat_Description {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_FileFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_FolderFormat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_FolderFormat {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_FolderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_FolderFormat_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_FolderFormat_Description {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_FolderFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_IsRemoved に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_IsRemoved {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_IsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Attribute_IsRemoved_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Attribute_IsRemoved_Description {
            get {
                return ResourceManager.GetString("ItemProperty_Attribute_IsRemoved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_DateTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_DateTime {
            get {
                return ResourceManager.GetString("ItemProperty_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_DateTime_CreationDate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_DateTime_CreationDate {
            get {
                return ResourceManager.GetString("ItemProperty_DateTime_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_DateTime_CreationDate_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_DateTime_CreationDate_Description {
            get {
                return ResourceManager.GetString("ItemProperty_DateTime_CreationDate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_DateTime_LastAccessTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_DateTime_LastAccessTime {
            get {
                return ResourceManager.GetString("ItemProperty_DateTime_LastAccessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_DateTime_LastAccessTime_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_DateTime_LastAccessTime_Description {
            get {
                return ResourceManager.GetString("ItemProperty_DateTime_LastAccessTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_DateTime_LastWriteTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_DateTime_LastWriteTime {
            get {
                return ResourceManager.GetString("ItemProperty_DateTime_LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_DateTime_LastWriteTime_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_DateTime_LastWriteTime_Description {
            get {
                return ResourceManager.GetString("ItemProperty_DateTime_LastWriteTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Name {
            get {
                return ResourceManager.GetString("ItemProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Name_FileName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Name_FileName {
            get {
                return ResourceManager.GetString("ItemProperty_Name_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Name_FileName_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Name_FileName_Description {
            get {
                return ResourceManager.GetString("ItemProperty_Name_FileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Name_FileType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Name_FileType {
            get {
                return ResourceManager.GetString("ItemProperty_Name_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Name_FileType_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Name_FileType_Description {
            get {
                return ResourceManager.GetString("ItemProperty_Name_FileType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Name_FullPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Name_FullPath {
            get {
                return ResourceManager.GetString("ItemProperty_Name_FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Name_FullPath_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Name_FullPath_Description {
            get {
                return ResourceManager.GetString("ItemProperty_Name_FullPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Size {
            get {
                return ResourceManager.GetString("ItemProperty_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Size_Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Size_Size {
            get {
                return ResourceManager.GetString("ItemProperty_Size_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ItemProperty_Size_Size_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemProperty_Size_Size_Description {
            get {
                return ResourceManager.GetString("ItemProperty_Size_Size_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoadedItemList_Caption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadedItemList_Caption {
            get {
                return ResourceManager.GetString("LoadedItemList_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoadedItemList_col_Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadedItemList_col_Name {
            get {
                return ResourceManager.GetString("LoadedItemList_col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoadedItemList_col_Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadedItemList_col_Type {
            get {
                return ResourceManager.GetString("LoadedItemList_col_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoadedItemList_Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadedItemList_Directory {
            get {
                return ResourceManager.GetString("LoadedItemList_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoadedItemList_File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadedItemList_File {
            get {
                return ResourceManager.GetString("LoadedItemList_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput_Caption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOutput_Caption {
            get {
                return ResourceManager.GetString("LogOutput_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput_col_CreatedDate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOutput_col_CreatedDate {
            get {
                return ResourceManager.GetString("LogOutput_col_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput_col_Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOutput_col_Level {
            get {
                return ResourceManager.GetString("LogOutput_col_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput_col_Logger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOutput_col_Logger {
            get {
                return ResourceManager.GetString("LogOutput_col_Logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput_col_Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOutput_col_Message {
            get {
                return ResourceManager.GetString("LogOutput_col_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput_lblCount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOutput_lblCount {
            get {
                return ResourceManager.GetString("LogOutput_lblCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput_lblLevel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOutput_lblLevel {
            get {
                return ResourceManager.GetString("LogOutput_lblLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LogOutput_lblLogger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOutput_lblLogger {
            get {
                return ResourceManager.GetString("LogOutput_lblLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TabControlEx_NoPage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabControlEx_NoPage {
            get {
                return ResourceManager.GetString("TabControlEx_NoPage", resourceCulture);
            }
        }
    }
}
