//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.App {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainMenuText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMenuText() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.App.MainMenuText", typeof(MainMenuText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   BUILD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Build {
            get {
                return ResourceManager.GetString("Menu_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DEBUG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Debug {
            get {
                return ResourceManager.GetString("Menu_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EDIT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FILE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HELP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PROJECT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Project {
            get {
                return ResourceManager.GetString("Menu_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOOL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Tool {
            get {
                return ResourceManager.GetString("Menu_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VIEW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WINDOW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu_Window {
            get {
                return ResourceManager.GetString("Menu_Window", resourceCulture);
            }
        }
    }
}
