//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YenconCommandLineTool.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YenconCommandLineTool.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   CommandNotFound {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileNotOpened に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotOpened {
            get {
                return ResourceManager.GetString("FileNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fname_Untitled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fname_Untitled {
            get {
                return ResourceManager.GetString("Fname_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_About {
            get {
                return ResourceManager.GetString("Man_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Adds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Adds {
            get {
                return ResourceManager.GetString("Man_Adds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Binhdr に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Binhdr {
            get {
                return ResourceManager.GetString("Man_Binhdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Exit {
            get {
                return ResourceManager.GetString("Man_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Goroot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Goroot {
            get {
                return ResourceManager.GetString("Man_Goroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Help {
            get {
                return ResourceManager.GetString("Man_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Help_Full に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Help_Full {
            get {
                return ResourceManager.GetString("Man_Help_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Into に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Into {
            get {
                return ResourceManager.GetString("Man_Into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_List {
            get {
                return ResourceManager.GetString("Man_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Loadb に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Loadb {
            get {
                return ResourceManager.GetString("Man_Loadb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Loadb_Full に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Loadb_Full {
            get {
                return ResourceManager.GetString("Man_Loadb_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Loadt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Loadt {
            get {
                return ResourceManager.GetString("Man_Loadt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Loadt_Full に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Loadt_Full {
            get {
                return ResourceManager.GetString("Man_Loadt_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Quit {
            get {
                return ResourceManager.GetString("Man_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Saveb に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Saveb {
            get {
                return ResourceManager.GetString("Man_Saveb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Saveb_Full に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Saveb_Full {
            get {
                return ResourceManager.GetString("Man_Saveb_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Savet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Savet {
            get {
                return ResourceManager.GetString("Man_Savet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Savet_Full に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Savet_Full {
            get {
                return ResourceManager.GetString("Man_Savet_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Set {
            get {
                return ResourceManager.GetString("Man_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Set_Full に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Set_Full {
            get {
                return ResourceManager.GetString("Man_Set_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Man_Ver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Man_Ver {
            get {
                return ResourceManager.GetString("Man_Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ManualNotFound {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ManualNotFound {
            get {
                return ResourceManager.GetString("ManualNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ManualTitle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ManualTitle {
            get {
                return ResourceManager.GetString("ManualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SectionNotFound に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SectionNotFound {
            get {
                return ResourceManager.GetString("SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShowBinHeader_Compatibility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowBinHeader_Compatibility {
            get {
                return ResourceManager.GetString("ShowBinHeader_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShowBinHeader_Implementation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowBinHeader_Implementation {
            get {
                return ResourceManager.GetString("ShowBinHeader_Implementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShowBinHeader_KeyNameSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowBinHeader_KeyNameSize {
            get {
                return ResourceManager.GetString("ShowBinHeader_KeyNameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShowBinHeader_KeyNameType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowBinHeader_KeyNameType {
            get {
                return ResourceManager.GetString("ShowBinHeader_KeyNameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShowBinHeader_Revision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowBinHeader_Revision {
            get {
                return ResourceManager.GetString("ShowBinHeader_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShowBinHeader_Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowBinHeader_Version {
            get {
                return ResourceManager.GetString("ShowBinHeader_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ToolTitle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolTitle {
            get {
                return ResourceManager.GetString("ToolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ver_Copyright に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ver_Copyright {
            get {
                return ResourceManager.GetString("Ver_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ver_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ver_Description {
            get {
                return ResourceManager.GetString("Ver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ver_Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ver_Version {
            get {
                return ResourceManager.GetString("Ver_Version", resourceCulture);
            }
        }
    }
}
