//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Core.GraphicalUIs {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormSearchReplaceTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormSearchReplaceTexts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Core.GraphicalUIs.FormSearchReplaceTexts", typeof(FormSearchReplaceTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   btnClose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   btnCount に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnCount {
            get {
                return ResourceManager.GetString("BtnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   btnNext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   btnRepAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnRepAll {
            get {
                return ResourceManager.GetString("BtnRepAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   btnReplace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BtnReplace {
            get {
                return ResourceManager.GetString("BtnReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FormSearchReplace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   labelDesc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelDesc {
            get {
                return ResourceManager.GetString("LabelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   labelNew に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelNew {
            get {
                return ResourceManager.GetString("LabelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   labelOld に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelOld {
            get {
                return ResourceManager.GetString("LabelOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   msgCount {0} : {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgCount {
            get {
                return ResourceManager.GetString("MsgCount", resourceCulture);
            }
        }
    }
}
