//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Core.Editors {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegistryDraftEditorTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistryDraftEditorTexts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Core.Editors.RegistryDraftEditorTexts", typeof(RegistryDraftEditorTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Identifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataGridView_Identifier {
            get {
                return ResourceManager.GetString("DataGridView_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataGridView_Type {
            get {
                return ResourceManager.GetString("DataGridView_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataGridView_Value {
            get {
                return ResourceManager.GetString("DataGridView_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   addnew に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Popup_AddNew {
            get {
                return ResourceManager.GetString("Popup_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   clear_select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Popup_ClearSelect {
            get {
                return ResourceManager.GetString("Popup_ClearSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Popup_Delete {
            get {
                return ResourceManager.GetString("Popup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Popup_Grid_Remove {
            get {
                return ResourceManager.GetString("Popup_Grid_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Popup_Open {
            get {
                return ResourceManager.GetString("Popup_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Popup_Rename {
            get {
                return ResourceManager.GetString("Popup_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no values. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Print_NoVals {
            get {
                return ResourceManager.GetString("Print_NoVals", resourceCulture);
            }
        }
    }
}
