//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSDeveloper.Core.Error {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSDeveloper.Core.Error.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   FileMetadata_FileCannotBeDir に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileMetadata_FileCannotBeDir {
            get {
                return ResourceManager.GetString("FileMetadata_FileCannotBeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IO_InvalidFileNameString: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IO_InvalidDirNameString {
            get {
                return ResourceManager.GetString("IO_InvalidDirNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IO_InvalidFileNameString: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IO_InvalidFileNameString {
            get {
                return ResourceManager.GetString("IO_InvalidFileNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IgnoredRootElement, Format: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SerializingException_IgnoredRootElement {
            get {
                return ResourceManager.GetString("SerializingException_IgnoredRootElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown, Format: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SerializingFailureState_Unknown {
            get {
                return ResourceManager.GetString("SerializingFailureState_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StringUtils_ConvertToBoolean, can&apos;t convert: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringUtils_ConvertToBoolean {
            get {
                return ResourceManager.GetString("StringUtils_ConvertToBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YenconBinaryFile_InvalidBitSize: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YenconBinaryFile_InvalidBitSize {
            get {
                return ResourceManager.GetString("YenconBinaryFile_InvalidBitSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YenconParser_UnknownCharacter, can&apos;t parse: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YenconParser_UnknownCharacter {
            get {
                return ResourceManager.GetString("YenconParser_UnknownCharacter", resourceCulture);
            }
        }
    }
}
